### ISSUE TITLE
cannot allocate memory error

### ISSUE THREAD

**Issue by dc217863** [masato-ka/ros2-docker#2]
Hi,
I am fairly new to docker containers in general so forgive my ignorance.

I tried the first example you provide. However, on trying to build the demo, i get the following error in my docker container.

> Finished <<< demo_nodes_py [0.72s]
Starting >>> quality_of_service_demo_cpp
--- stderr: dummy_map_server
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/dummy_map_server.dir/build.make:63: CMakeFiles/dummy_map_server.dir/src/dummy_map_server.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/dummy_map_server.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Failed   <<< dummy_map_server [12.9s, exited with code 2]
Aborted  <<< dummy_sensors [12.9s]
Aborted  <<< demo_nodes_cpp_native [13.0s]
[14.747s] ERROR:colcon.colcon_core.event_reactor:Exception in event handler extension 'event_log': [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/event_reactor.py", line 78, in _notify_observers
    retval = observer(event)
  File "/usr/lib/python3/dist-packages/colcon_output/event_handler/event_log.py", line 50, in __call__
    self._file_handle.flush()
OSError: [Errno 12] Cannot allocate memory

At the start of build I get the following warning:

> Start build
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

Any suggestion on how to solve this?

Thanks!

**Comment by masato-ka** [comment]
I think, docker daemon can not enough memory on your machine. How much memory allocate to docker daemon ?
My machine allocate 8GB memory to docker.

**Comment by dc217863** [comment]
Thanks for your reply. A simple restart solved my issues.

I am now able to run the first tutorial.

One more question: how to stop? Ctrl+C in the terminal with launch gives me:

> ^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)

and then does not really stop.

**Comment by masato-ka** [comment]
Sorry, this is problem. Now I do not success stop process by Ctrl+C.  Always use stop docker container.
